M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sel 05 Sep 2023 02:51:34 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-05T14:51:34+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X6.3752Y-4.2669
X6.6894Y-4.2669
T0
M30
