M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Sen 06 Nov 2023 08:13:10 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T20:13:10+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.0421Y-5.5453
X5.3563Y-5.5453
T0
M30
